server.port=${BFF_SERVER_PORT:8080}

spring.application.name=bff
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID:092406df-0491-4c9e-8221-43d77ece03ff}/v2.0
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID:092406df-0491-4c9e-8221-43d77ece03ff}/discovery/v2.0/keys

azure.activedirectory.tenant-id=${AZURE_TENANT_ID:092406df-0491-4c9e-8221-43d77ece03ff}
azure.activedirectory.client-id=${AZURE_CLIENT_ID:b419846b-7b38-46ba-96a5-7e18e287a476}
azure.activedirectory.app-id-uri=${AZURE_APP_ID_URI:api://b419846b-7b38-46ba-96a5-7e18e287a476}
azure.activedirectory.frontend-client-id=${AZURE_FRONTEND_CLIENT_ID:e0f115f7-d16f-4f4f-88e8-959e891083e2}

microservice.pedidos-backend.url=${MICROSERVICE_PEDIDOS_URL:http://localhost:4545}

logging.level.org.springframework.security=DEBUG
logging.level.com.duocuc.bff=DEBUG
